'use strict';

// Generated by scripts/update-assets.js.
const CACHE_PREFIX = 'yog1-';
const CACHE = 'yog1-ced7846c99f5';
const FILES = [
    './index.html',
    './yog1.htm',
    './assets/css/game.css',
    './assets/js/theme.js',
    './assets/js/locales.js',
    './assets/js/locale-loader.js',
    './assets/js/storage.js',
    './assets/js/game-core.js',
    './assets/js/i18n.js',
    './assets/js/game-content.js',
    './assets/js/version.js',
    './assets/js/gamepad.js',
    './assets/js/game.js',
    './assets/manifests/manifest.webmanifest',
    './assets/manifests/manifest.es.webmanifest',
    './assets/manifests/manifest.de.webmanifest',
    './assets/manifests/manifest.fr.webmanifest',
    './assets/manifests/manifest.zh.webmanifest',
    './assets/manifests/manifest.zh-Hant.webmanifest',
    './assets/manifests/manifest.ar.webmanifest',
    './assets/manifests/manifest.bn.webmanifest',
    './assets/manifests/manifest.ja.webmanifest',
    './assets/manifests/manifest.ko.webmanifest',
    './assets/manifests/manifest.hi.webmanifest',
    './assets/manifests/manifest.pt.webmanifest',
    './assets/manifests/manifest.pl.webmanifest',
    './assets/manifests/manifest.ru.webmanifest',
    './assets/manifests/manifest.vi.webmanifest',
    './assets/manifests/manifest.tr.webmanifest',
    './assets/manifests/manifest.ur.webmanifest',
    './assets/icons/icon.svg',
    './assets/icons/icon-192.png',
    './assets/icons/icon-512.png'
];
// Locale bundles are fetched and runtime-cached only when selected.
const LAZY_FILES = [
    './assets/js/translations/es.js',
    './assets/js/translations/de.js',
    './assets/js/translations/fr.js',
    './assets/js/translations/zh.js',
    './assets/js/translations/zh-Hant.js',
    './assets/js/translations/ar.js',
    './assets/js/translations/bn.js',
    './assets/js/translations/ja.js',
    './assets/js/translations/ko.js',
    './assets/js/translations/hi.js',
    './assets/js/translations/pt.js',
    './assets/js/translations/pl.js',
    './assets/js/translations/ru.js',
    './assets/js/translations/vi.js',
    './assets/js/translations/tr.js',
    './assets/js/translations/ur.js'
];

self.addEventListener('install', function (event) {
    event.waitUntil(caches.open(CACHE).then(function (cache) {
        return cache.addAll(FILES);
    }).then(function () {
        return self.skipWaiting();
    }));
});

self.addEventListener('activate', function (event) {
    event.waitUntil(caches.keys().then(function (keys) {
        return Promise.all(keys.filter(function (key) {
            return key.startsWith(CACHE_PREFIX) && key !== CACHE;
        }).map(function (key) {
            return caches.delete(key);
        }));
    }).then(function () {
        return self.clients.claim();
    }));
});

self.addEventListener('message', function (event) {
    if (!event.data) return;
    if (event.data.type === 'cache-all-locales') {
        event.waitUntil(caches.open(CACHE).then(function (cache) {
            return Promise.all(LAZY_FILES.map(function (path) {
                return cache.add(path).catch(function () {
                    // One unavailable translation must not prevent the rest from installing.
                });
            }));
        }));
        return;
    }
    if (event.data.type !== 'cache-locale') return;
    const requested = './' + String(event.data.path || '').replace(/^\.?\//, '');
    if (!LAZY_FILES.includes(requested)) return;
    event.waitUntil(caches.open(CACHE).then(function (cache) {
        return cache.add(requested);
    }));
});

self.addEventListener('fetch', function (event) {
    if (event.request.method !== 'GET') return;
    if (new URL(event.request.url).origin !== self.location.origin) return;
    event.respondWith(caches.open(CACHE).then(function (cache) {
        return cache.match(event.request, {
            ignoreSearch: event.request.mode === 'navigate'
        }).then(function (cached) {
            return cached || fetch(event.request).then(function (response) {
                if (!response.ok) return response;
                const copy = response.clone();
                return cache.put(event.request, copy).catch(function () {
                    // A full or unavailable runtime cache must not break the network response.
                }).then(function () {
                    return response;
                });
            }).catch(function () {
                if (event.request.mode === 'navigate') {
                    return cache.match('./index.html');
                }
                throw new Error('Offline and resource was not cached');
            });
        });
    }));
});
