'use strict';

// Generated by scripts/update-assets.js.
const CACHE_PREFIX = 'yog1-';
const CACHE = 'yog1-a932d604813c';
const FILES = [
    './yog1.htm',
    './locales.js',
    './storage.js',
    './game-core.js',
    './i18n.js',
    './game-content.js',
    './version.js',
    './game.js',
    './manifest.webmanifest',
    './manifest.es.webmanifest',
    './manifest.zh.webmanifest',
    './manifest.ar.webmanifest',
    './manifest.bn.webmanifest',
    './manifest.ja.webmanifest',
    './manifest.hi.webmanifest',
    './manifest.pt.webmanifest',
    './manifest.ru.webmanifest',
    './manifest.vi.webmanifest',
    './manifest.tr.webmanifest',
    './manifest.ur.webmanifest',
    './icon.svg',
    './icon-192.png',
    './icon-512.png'
];

self.addEventListener('install', function (event) {
    event.waitUntil(caches.open(CACHE).then(function (cache) {
        return cache.addAll(FILES);
    }).then(function () {
        return self.skipWaiting();
    }));
});

self.addEventListener('activate', function (event) {
    event.waitUntil(caches.keys().then(function (keys) {
        return Promise.all(keys.filter(function (key) {
            return key.startsWith(CACHE_PREFIX) && key !== CACHE;
        }).map(function (key) {
            return caches.delete(key);
        }));
    }).then(function () {
        return self.clients.claim();
    }));
});

self.addEventListener('fetch', function (event) {
    if (event.request.method !== 'GET') return;
    if (new URL(event.request.url).origin !== self.location.origin) return;
    event.respondWith(caches.open(CACHE).then(function (cache) {
        return cache.match(event.request, {
            ignoreSearch: event.request.mode === 'navigate'
        }).then(function (cached) {
            return cached || fetch(event.request).then(function (response) {
                if (!response.ok) return response;
                const copy = response.clone();
                return cache.put(event.request, copy).catch(function () {
                    // A full or unavailable runtime cache must not break the network response.
                }).then(function () {
                    return response;
                });
            }).catch(function () {
                if (event.request.mode === 'navigate') {
                    return cache.match('./yog1.htm');
                }
                throw new Error('Offline and resource was not cached');
            });
        });
    }));
});
