'use strict';

const crypto = require('crypto');
const fs = require('fs');
const path = require('path');
const vm = require('vm');

const root = path.resolve(__dirname, '..');
const document = {
    documentElement: {},
    querySelectorAll: function () { return []; }
};
const storage = new Map();
const context = {
    URLSearchParams: URLSearchParams,
    navigator: { language: 'en' },
    localStorage: {
        getItem: function (key) { return storage.get(key) || null; },
        setItem: function (key, value) { storage.set(key, value); }
    },
    document: document,
    window: { location: { search: '' } }
};
context.window.window = context.window;
context.window.navigator = context.navigator;
context.window.localStorage = context.localStorage;
context.window.document = document;

vm.runInNewContext(fs.readFileSync(path.join(root, 'assets/js/locales.js'), 'utf8'), context, {
    filename: 'assets/js/locales.js'
});
const localeBundles = context.window.Yog1Locales.filter(function (locale) {
    return locale.id !== 'en';
}).map(function (locale) {
    return 'assets/js/translations/' + locale.id + '.js';
});
for (const filename of localeBundles.concat(['assets/js/i18n.js'])) {
    vm.runInNewContext(fs.readFileSync(path.join(root, filename), 'utf8'), context, {
        filename: filename
    });
}

const i18n = context.window.Yog1I18n;
const icons = [
    { src: '../icons/icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
    { src: '../icons/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
    { src: '../icons/icon.svg', sizes: 'any', type: 'image/svg+xml', purpose: 'any' }
];
const manifests = [];
for (const locale of i18n.localeOptions) {
    const filename = locale.id === 'en'
        ? 'assets/manifests/manifest.webmanifest'
        : 'assets/manifests/manifest.' + locale.id + '.webmanifest';
    const manifest = {
        name: 'You Only Get 1s',
        short_name: 'YOG1',
        lang: locale.tag
    };
    if (locale.direction === 'rtl') manifest.dir = 'rtl';
    Object.assign(manifest, {
        description: i18n.locales[locale.id]['meta.description'],
        start_url: '../../?lang=' + locale.id,
        scope: '../../',
        display: 'standalone',
        background_color: '#191919',
        theme_color: '#191919',
        icons: icons
    });
    fs.writeFileSync(path.join(root, filename), JSON.stringify(manifest, null, 2) + '\n');
    manifests.push(filename);
}

const files = [
    'index.html', 'assets/js/locales.js', 'assets/js/locale-loader.js',
    'assets/js/storage.js', 'assets/js/game-core.js', 'assets/js/i18n.js',
    'assets/js/game-content.js', 'assets/js/version.js', 'assets/js/game.js'
].concat(manifests, [
    'assets/icons/icon.svg', 'assets/icons/icon-192.png', 'assets/icons/icon-512.png'
]);
const hash = crypto.createHash('sha256');
for (const filename of files.concat(localeBundles)) {
    const contents = fs.readFileSync(path.join(root, filename));
    hash.update(filename).update('\0');
    hash.update(String(contents.length)).update('\0');
    hash.update(contents);
}
const cacheName = 'yog1-' + hash.digest('hex').slice(0, 12);

const serviceWorkerPath = path.join(root, 'sw.js');
const serviceWorker = fs.readFileSync(serviceWorkerPath, 'utf8');
const handlerStart = serviceWorker.indexOf("self.addEventListener('install'");
if (handlerStart < 0) throw new Error('Could not find service worker event handlers.');
const handlers = serviceWorker.slice(handlerStart);
const fileList = files.map(function (filename) {
    return "    './" + filename + "'";
}).join(',\n');
const lazyFileList = localeBundles.map(function (filename) {
    return "    './" + filename + "'";
}).join(',\n');
const generated = "'use strict';\n\n" +
    "// Generated by scripts/update-assets.js.\n" +
    "const CACHE_PREFIX = 'yog1-';\n" +
    "const CACHE = '" + cacheName + "';\n" +
    'const FILES = [\n' + fileList + '\n];\n' +
    '// Locale bundles are fetched and runtime-cached only when selected.\n' +
    'const LAZY_FILES = [\n' + lazyFileList + '\n];\n\n' + handlers;
fs.writeFileSync(serviceWorkerPath, generated);

console.log('Updated ' + manifests.length + ' manifests and offline cache ' + cacheName + '.');
